version: "3"

services:
    db:
        container_name: db_blog
        image: postgres:9.6
        networks:
            - dev_api
        environment:
            - POSTGRES_PASSWORD=passwd
            - POSTGRES_DB=blog
        volumes:
            - dev_postgresql:/var/lib/postgresql
            - dev_postgresql_data:/var/lib/postgresql/data
        ports: 
            - 5434:5432    

    mongodb:
        container_name: db_mongo
        image: mongo
        networks:
            - dev_api
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=root
        volumes:
            - dev_mongofile:/data/db
    
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8088:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: root        

networks:
    dev_api:

volumes:
    dev_postgresql:
    dev_postgresql_data:
    dev_mongofile: 